version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: "/"
    labels: []
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      time: "04:00"
    commit-message:
      prefix: "bot(deps): "
    target-branch: main
    assignees:
      - seekinginfiniteloop
    groups:
      all:
        applies-to: security-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    open-pull-requests-limit: 10
    directory: "/"
    labels: []
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      time: "04:00"
    commit-message:
      prefix: "bot(deps): "
    target-branch: main
    assignees:
      - seekinginfiniteloop
    groups:
      all:
        applies-to: security-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    versioning-strategy: increase
    directory: "/"
    labels: []
    schedule:
      interval: weekly
      time: "04:00"
    commit-message:
      prefix: "bot(deps): "
    target-branch: main
    assignees:
      - seekinginfiniteloop
    groups:
      all:
        applies-to: security-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "bot(deps): "
    target-branch: main
    assignees:
      - seekinginfiniteloop
    groups:
      all:
        update-types:
          - minor
          - patch
