rule_settings:
  enable:
    - default
    - gpsg
  disable:
    - dont-self-assign-variables
  python_version: '3.12'
  rule_types:
    - refactoring
    - suggestion
    - comment

ignore:
  - node_modules
  - .git
  - .venv
  - tox
  - vendor
  - external
  - env
  - .env
  - .tox
  - node_modules
  - .venv
  - env
  - .env
  - /usr/*
  - /usr/share/code/*
  - /user/share/code/resources/app/extensions//node_modules/.*
  - /usr/share/code/**/.*
  - /tools/**/*.js
  - /.github/**/*.js
  - /docs/assets/**/*.js
