site_name: PlainLicense
site_url: https://plainlicense.org
repo_url: https://github.com/seekinginfiniteloop/PlainLicense
repo_name: PlainLicense
edit_uri: edit/dev/docs/default-monochrome.svg
copyright: All PlainLicense materials are [dedicated to the public domain]().
theme:
  name: material
  logo: assets/logo/vector/icon_only.svg
  favicon: assets/logo/vector/icon_only.svg
  font:
    text: Noto Sans
    code: Noto Sans Mono
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
plugins:
  - blog
  - offline
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - social:
      cards_layout_options:
        font_family: Raleway
        background_color: "#1AB5E6"
        color: "#FFFFFF"
  - tags
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - def_list
  - tables
  - toc:
        - toc-depth: 3
        - permalink_title: Anchor link to this section to use for sharing
        - permalink: true
        - slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower, percent_encode: true}}
          permalink: "\ue157"
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/feedback.js

extra:
  alternate:
    - name: English
      link: /
      lang: en
  analytics:
    property: custom
    provider: tinyanalytics
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by
#            filing an issue:
#            https://github.com/seekinginfiniteloop/PlainLicense/issues/new/?title=[Feedback]+{title}+-+{url}
# TODO: Add feedback form; need custom logic since tinyanalytics doesn't support it
