site_name: Plain License
site_url: https://plainlicense.org
repo_url: https://github.com/seekinginfiniteloop/PlainLicense
repo_name: PlainLicense
edit_uri: edit/dev/docs/
copyright: Plain License and its creators dedicate all original content to the public domain. No rights reserved.
site_description: At Plain License, we simplify legal writing to remove the confusion of "legalese" that blocks innovation and creativity. Our mission is to provide clear, easy-to-understand license terms. We offer plain versions of popular licenses like the MIT License, the Apache License, and the GPL. We also create new, simple licenses that anyone can use.
nav:
  - Home: index.md
theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/logo.jpg
  font:
    text: Raleway
    code: Noto Sans Mono
  language: en
  palette:
    scheme: slate
    primary: custom
    accent: custom
extra_css:
  - splash.css

not_in_nav: |
  overrides/*
