site_name: PlainLicense
theme:
  name: material

nav:
  - English:
      - Home: en/index.md
      - Licenses:
        - en/licenses/en_PlainAGPLv3.md
        - en/licenses/en_PlainApachev2.md
        - en/licenses/en_PlainBSDv2.md
        - en/licenses/en_PlainGPLv2.md
        - en/licenses/en_PlainGPLv3.md
        - en/licenses/en_PlainLGPLv2.md
        - en/licenses/en_PlainLGPLv3.md
        - en/licenses/en_PlainMITvNone.md
        - en/licenses/en_PlainMPLv2.md
        - en/licenses/en_PlainUnlicense.md
