site_name: Plain License
site_url: https://plainlicense.org
repo_url: https://github.com/seekinginfiniteloop/PlainLicense
repo_name: PlainLicense
edit_uri: edit/dev/docs/
copyright: Plain License's authors dedicate all original content to the public domain. No rights reserved.
hooks:
  - overrides/hooks/socialmedia.py
  - overrides/hooks/update_changelogs.py
  - overrides/hooks/content_assembly.py
site_description: |
  Plain License: Terms for Everyone.

  Licenses are difficult to read and understand. That prevents innovation and creativity. Our mission is to provide clear, easy-to-understand license terms. We offer plain versions of popular licenses like the MIT License, the Mozilla Public License 2.0, and the Unlicense. We will make licensing accessible to everyone, regardless of their background, experience, or education.
nav:
  - home: index.md
  - about:
      - about/index.md
  - faq:
      - faq/index.md
  - our licenses:
      - licenses/index.md
      - public domain:
          - licenses/public-domain/index.md
          - Unlicense: licenses/public-domain/unlicense/index.md
      - permissive licenses:
          - licenses/permissive/index.md
          - MIT: licenses/permissive/mit/index.md
      - copyleft licenses:
          - licenses/copyleft/index.md
          - MPL: licenses/copyleft/mpl-2.0/index.md
      - source-available licenses:
          - licenses/source-available/index.md
          - Elastic License: licenses/source-available/elastic-2.0/index.md
      - proprietary licenses:
          - licenses/proprietary/index.md
  - help us:
      - helping/index.md
    # - Coding: helping/code.md
    # - Donate: helping/donate.md
    # - Crafting: helping/crafting.md
    # - Legal Feedback: helping/legal.md
    # - Translate: helping/translate.md
  - blog: blog/index.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/named_logo.png
  favicon: assets/images/favicon.png
  font:
    text: Noto Sans
    code: Noto Sans Mono
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: simple/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for system automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt_max_categories: 3
      categories_allowed:
        - plain writing
        - announcements
        - updates
        - community
        - how-to
      draft_if_future_date: true
  - offline
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - social:
      cards_layout_options:
        font_family: Raleway
        color: "#FFFFFF"
        background_color: "#0d19a3"
        image: assets/images/logo_only_color_transp.png
  - tags
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - markdown.extensions.meta
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify {
          kwds: { case: lower, percent_encode: true, combine_header_slug: true },
        }
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      default_lang: markdown
      guess_lang: true
      line_spans: __span
      use_pygments: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.mark
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      social_url_shortener: true
      repo_url_shorthand:
      social_url_shorthand: true
      provider: github
      user: seekinginfiniteloop
      repo: PlainLicense
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      toc_depth: 3
      permalink_title: An anchor link you can use to share this section
      permalink: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify {
          kwds: { case: lower, percent_encode: true },
        }
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/images/javascripts/counter.js
  #- assets/javascripts/feedback.js
  - assets/images/javascripts/tablesort.js
extra_css:
  - assets/stylesheets/colors.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/license.css
  #- assets/stylesheets/landing.css
watch:
  - includes
not_in_nav: |
  index*
  CHANGELOG*
extra:
  analytics:
    provider: tinyanalytics
  boilerplate:
    # boilerplate for licenses; you don't need to change this
    # placeholders are replaced when rendering the license from the license frontmatter
    description: >
      Plain License: {{ plain_name|trim }}. Terms for everyone. The {{ original_name|trim }}, but now in plain language for everyone to understand.
    plain_url: >
      /licenses/{{ category.lower()|trim }}/{{ spdx_id.lower()|trim }}/
    github_base_url: >
      https://github.com/seekinginfiniteloop/PlainLicense
    github_issues_link: >
      [submit an issue](https://github.com/seekinginfiniteloop/PlainLicense/issues/new/choose "Submit an issue on GitHub")
    github_edit_link: >
      [edit yourself](https://github.com/seekinginfiniteloop/PlainLicense/edit/main/docs/licenses/{{ category.lower()|trim }}/{{ spdx_id.lower()|trim }}/index.md "Edit this license on GitHub")
    hide: # list of mkdocs components to hide in licenses
    official_link: >
      [{{ original_name|trim }}]({{ original_url|trim }} "Official {{ original_name|trim }}")
    interpretation_title: >
      **Legally Interpreting the {{ plain_name|trim }}**
    interpretation_text: |
      The {{ plain_name|trim }} is a plain language adaptation of the {{ original_name|trim }}. We made the {{ plain_name|trim }} to make the {{ original_name|trim }} more accessible and understandable. We tried to match the {{ original_name|trim }}'s legal intent exactly. **If you feel the {{ plain_name|trim }}'s terms are legally unclear, use the official {{ official_link|trim }} to clarify the terms.**

      If a court finds that any part of this {{ license_type|trim }} cannot be enforced, the rest of the {{ license_type|trim }} will still apply.
