site_name: Plain License
site_url: https://plainlicense.org
repo_url: https://github.com/seekinginfiniteloop/PlainLicense
repo_name: PlainLicense
edit_uri: edit/main/docs/
copyright: Plain License's authors dedicate all original content to the public domain. No rights reserved.
hooks:
  - overrides/hooks/license_canary.py # Tests build process for errors to prevent broken builds
  - overrides/hooks/hook_logger.py # Central logger for hooks (can also do plugins)
  - overrides/hooks/socialmedia.py # Material hook for social media cards
  - overrides/hooks/update_changelogs.py # Handles changelog updates for individual licenses
  - overrides/hooks/content_assembly.py # Assembles licenses from frontmatter and boilerplate (boilerplate here in the config)
  - overrides/hooks/env_settings.py # Adds to the jinja environment
  - overrides/hooks/update_site_license.py # Updates the site license to match the latest Plain Unlicense
site_description: >
  Plain License: Terms for Everyone.
nav:
  - home: index.md
  - about: about/index.md
  - faq: faq/index.md
  - our licenses:
      - licenses/index.md
      - public domain:
          - licenses/public-domain/index.md
          - Unlicense: licenses/public-domain/unlicense/index.md
      - permissive licenses:
          - licenses/permissive/index.md
          - MIT: licenses/permissive/mit/index.md
      - copyleft licenses:
          - licenses/copyleft/index.md
          - MPL: licenses/copyleft/mpl-2.0/index.md
      - source-available licenses:
          - licenses/source-available/index.md
          - Elastic License: licenses/source-available/elastic-2.0/index.md
      - proprietary licenses:
          - licenses/proprietary/index.md
  - help:
      - helping/index.md
      - craft: helping/craft.md
      - write: helping/write.md
      - legal: helping/legal.md
      - translate: helping/translate.md
      - code: helping/code.md
      - donate: helping/donate.md
  - blog: blog/index.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo_named.svg
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.footnote.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: simple/github
    edit: material/pencil
    view: material/eye
    tag: # These are the icons for the tags in the license frontmatter. They map to the tag name in the license frontmatter.
      canshare: octicons/share-24
      cansell: fontawesome/solid/money-bill-1
      canchange: material/file-edit
      canrevoke: nounproject/revoke
      required: nounproject/required
      allowed: nounproject/allowed
      relicense: nounproject/relicense
      copyleft: nounproject/copyleft
      givecredit: nounproject/copyright
      describechanges: octicons/file-diff-24
      sharesource: octicons/book-24
  palette:
    # Palette toggle for system automatic mode; chooses the color scheme based on the user's system preference, but allows the user to override it.
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt_max_categories: 3
      categories_allowed: # all blog entries must have at least one of these categories, and cannot have any other categories
        - plain writing
        - announcements
        - updates
        - community
        - how-to
        - licensing
      draft_if_future_date: true
  - macros
  - offline
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  #- shame_counter
  - social:
      cards_layout_options:
        font_family: Raleway
        color: "#FFFFFF"
        background_color: "#0d19a3"
        image: overrides/images/social_logo.png
  - tags:
      tags: true
      enabled: true
      tags_file: tags.md
  - privacy:
      assets: true
      assets_fetch: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - markdown.extensions.meta
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      default_lang: markdown
      guess_lang: true
      line_spans: __span
      use_pygments: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.mark
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      social_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      provider: github
      user: seekinginfiniteloop
      repo: PlainLicense
  - pymdownx.progressbar:
      progress_increment: 20
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path:
        - /
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.striphtml:
      strip_comments: true
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      toc_depth: 3
      permalink_title: An anchor link you can use to share this section
      permalink: true
watch:
  - includes
  - overrides
  - mkdocs.yml
not_in_nav: |
  index*
  CHANGELOG*
  tags
  shame*
extra:
  tags: # maps the tags in the license front matter to the names above in theme.icon.tag. This allows us to replace the tag with an icon in the license template.
    can-share: canshare
    can-sell: cansell
    can-change: canchange
    can-revoke: canrevoke
    relicense: relicense
    share-alike (strict): copyleft
    share-alike (relaxed): copyleft
    give-credit: givecredit
    describe-changes: describechanges
    share-source: sharesource
  boilerplate:
    # boilerplate for licenses; you don't need to change this
    # The placeholders (e.g. {{ original_name | trim }}) are jinja2 placeholders and are replaced with the values in the license frontmatter when the license is built.
    description: >
      Plain License: {{ plain_name | trim }}. Terms for everyone. The {{ original_name | trim }}, but now in plain language for everyone to understand.
    plain_url: >
      "licenses/{{ category.lower() | trim }}/{{ spdx_id.lower() | trim }}/"
    github_base_url: >
      https://github.com/seekinginfiniteloop/PlainLicense
    github_issues_link: >
      [submit an issue](https://github.com/seekinginfiniteloop/PlainLicense/issues/new/choose "Submit an issue on GitHub")
    github_edit_link: >
      [edit this page](https://github.com/seekinginfiniteloop/PlainLicense/edit/main/docs/licenses/{{ category.lower() | trim }}/{{ spdx_id.lower() | trim }}/index.md "Edit this license on GitHub")
    hide: # list of mkdocs components to hide in licenses; the table of contents is already hidden in the license template.
    official_link: >
      [{{ original_name | trim }}]({{ original_url | trim }} "Official {{ original_name | trim }}")
    interpretation_title: >
      Legally Interpreting the {{ plain_name | trim }}
    interpretation_text: |
      The {{ plain_name | trim }} is a plain language adaptation of the {{ original_name | trim }}. We made the {{ plain_name | trim }} to make the {{ original_name | trim }} more accessible and understandable. We tried to match the {{ original_name | trim }}'s legal intent exactly. **If you think the {{ plain_name | trim }}'s terms are legally unclear, use the official {{ official_link | trim }} to clarify the terms.**

      If a court finds that any part of this {{ license_type | trim }} cannot be enforced, the rest of the {{ license_type | trim }} will still apply.
    how: |
      Create a LICENSE or LICENSE.md file in the base of your project. If your project is on Github or another platform that uses markdown, copy the <a class="how_link" href=#markdown>markdown version</a> using the copy icon. If your platform doesn't support markddown, use the <a class="how_link" href="#plaintext">plaintext version</a>, or provide a link to our <a class="how_link" href="#reader">reader version</a>. **Notices**: the licensing community usually recommends adding a short notice to each part of your project telling readers how the work is licensed. For software projects, this is at the top of each module or file. <a class="how_link" href="#notice">Get the notice for the {{ plain_name | trim }}</a>.
    tag_text: # These values map to each of the tags in the license frontmatter, and are used for tooltips.
      can-share: >
        Share Freely: You can share or distribute any work that uses this {{ license_type | trim }} freely.
      can-sell: >
        Use Commercially: You can sell any work that uses this {{ license_type | trim }}, and you don't have to pay the authors anything or share your changes with them.
      can-change: >
        Change freely: You can change any work that uses this {{ license_type | trim }} however you want.
      can-revoke: >
        Taksies-backsies: You can revoke this license from any work that uses it at any time if you hold the copyright.
      relicense: >
        Relicense: You can change the {{ license_type | trim }} to a different license if you want. You may need to follow certain rules, like giving credit to the original author.
      share-alike (strict): >
        Share-Alike (strict): You must share your changes under the same license if you change or modify any work that uses this license.
      share-alike (relaxed): >
        Share-Alike (relaxed): You must share your changes under the same license or a similar one if you change or modify any work that uses this license.
      give-credit: >
        Give Credit: You must give credit to the original author of any work that uses this license, usually by including their name and the original license in your work.
      describe-changes: >
        Describe Changes: You must describe any changes you make to any work that uses this license.
      share-source: >
        Share Your Work: You must share the source code of any work that uses this license.
  extensions: # These are the extensions we use in our documentation for making the most of markdown for writing plainly. They map the extension name in markdown_extensions to a human-readable name, a URL to the extension's documentation, and a description of what the extension does.
    abbr:
      name: abbreviations and acronyms
      url: >
        https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations "Adding abbreviations and acronyms with tooltips"
      description: >
        Add abbreviations and acronyms with tooltips. You can do this sitewide by adding to [abbreviations.md](https://github.com/seekinginfiniteloop/PlainLicense/edit/main/includes/abbreviations.md "/includes/abbreviations.md") or on a per-page basis.
    betterem:
      name: better emphasis
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/betterem/ "Better emphasis in markdown"
      description: Adds support for smarter emphasis in markdown, including nested emphasis and better handling of underscores.
    admonition:
      name: admonitions (blocks API)
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/ "Adding callout boxes with the blocks API"
      description: Add callout boxes. Use this to highlight important information or warnings.
    details:
      name: collapsible details (blocks API)
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/details/ "Adding collapsible detail blocks with the blocks API"
      description: Add collapsible detail blocks. By default, they start collapsed.
    critic:
      name: critic markup
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/critic/ "Adding critic markup to markdown"
      description: >
        Add [critic markup](http://criticmarkup.com/). Use this to suggest changes or make comments.
    def_list:
      name: definition lists
      url: >
        https://squidfunk.github.io/mkdocs-material/reference/lists/?h=def+list "Adding definition lists"
      description: Add definition lists. Use this to define terms or concepts.
    emoji:
      name: emoji and icons
      url: >
        https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/ "Adding emoji and icons"
      description: Add emoji and icons. Use this to add visual interest or to convey meaning.
    footnotes:
      name: footnotes
      url: >
        https://squidfunk.github.io/mkdocs-material/reference/footnotes/ "Adding footnotes"
      description: Add footnotes to provide additional information or context. Use this to avoid cluttering.
    mark:
      name: mark text (highlight)
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/mark/ "Highlight text in markdown"
      description: Add the ability to highlight text. Use this to draw attention to important information.
    smartsymbols:
      name: smart symbols
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/ "Adding smart symbols to markdown"
      description: >
        Easily add special characters and symbols without needing to remember the code. One we use a lot here: `(c)` for copyright (c).
    tables:
      name: tables
      url: >
        https://squidfunk.github.io/mkdocs-material/reference/data-tables/ "Adding sortable tables"
      description: Add sortable tables.
    tilde:
      name: tilde strikethrough
      url: >
        https://facelessuser.github.io/pymdown-extensions/extensions/tilde/ "Adding strikethrough text with tildes"
      description: Use strikethrough text with tildes. Use this to show deleted text or to indicate changes.
  shame_words: # These are 'shame words' for calculating the wall of shame (forthcoming). We use this list to determine how many 'shame words' are in the original license. The values are plain language alternatives to the more complex terms.
    # TODO: Change implementation to use the stem or lexxer of the word as the key, and the plain language alternative as the value so we don't have to list every form of the word.
    absence: lack
    additional: more
    alter: change
    ancillary: supporting
    apparatus: tool
    applicable: related
    arising from: caused by
    arising: caused by
    combination: mix
    compatibility: ability to work together
    compatible: able to work together
    compliance: following the rules
    comply: follow
    consequential: related
    constitute: make up
    construed: understood
    convey: share
    conveyance: sharing
    detriment: harm
    display: show
    distribute: share
    distributes: shares
    effectuate: carry out
    enforce: make sure the rules are followed
    enforcement: making sure the rules are followed
    entity: person or organization
    equivalent: same, similar
    exclusion: not included
    exercise: use
    exercising: using
    exploit: use
    express: say, state
    expressed: said, stated
    expressly: clearly
    fitness: ability
    furnished: given
    grant: give
    hereby: now
    hereof: this
    hereunder: in this
    implied: suggested
    impossible: can't
    incompatible: not able to work together
    indemnify: protect
    infringed: violated
    infringements: violations
    interest: share in
    invalid: not valid
    irrevocable: permanent
    jurisdiction: area of law, place where the law applies, court
    licenseable: can license
    licensee: user
    licensees: users
    licensor: creator, author
    licensors: creators, authors
    litigation: lawsuit
    location: place
    merchantability: good enough to sell
    merchantable: good enough to sell
    modification: change
    modified: changed
    modify: change
    moreover: also
    non-exclusive: not the only, shared
    noninfringement: not violating
    notwithstanding: despite, including
    obligation: duty, responsibility, requirement
    obscure: hide
    obtaining: getting
    on behalf of: for
    perform: do
    permit: allow
    permitted: allowed
    prohibited: not allowed
    propagate: share or spread
    proprietary: owned
    provisions: rules
    publish: share
    regulation: rule
    relinquish: give up
    relinquishment: giving up
    remedy: fix, make right
    reproduce: copy
    royalty-free: free
    shall: will
    statute: law
    steward: caretaker
    stewardship: care
    sublicensable: can license
    subsequent: later
    survive: last, continue
    terminate: end
    termination: end
    thereof: that
    third party: other person or organization
    unencumbered: free
    unmodified: unchanged
    with respect to: about
