exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
extend-include = ["*.ipynb"]


fix = true
line-length = 100
indent-width = 4

target-version = "py310"



[format]
docstring-code-format = true
docstring-code-line-length = 80
line-ending = "auto"
indent-style = "space"

skip-magic-trailing-comma = true

exclude = [
    "**/_vendor",
    "setuptools/_distutils",
    "setuptools/config/_validate_pyproject",
    ".venv",
    ".git",
    ".github",
    ".vscode",
    ".idea",
    "dist",
    "build",
    "site",
    "bin",
    "lib",
    "include",
    "docs",
]
# Enable preview, required for quote-style = "preserve"
preview = true
# https://docs.astral.sh/ruff/settings/#format-quote-style
quote-style = "double"

[lint]

fixable = ["ALL"]
select = [
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "LOG",
    "PD",
    "S",
    "SIM",
    "UP",
    "YTT",
    "W",
]
extend-select = [
    "A003",
    "ASYNC100",
    "ASYNC101",
    "ASYNC102",
    "ANN201",
    "ANN002",
    "COM818",
    "C901",
    "DTZ005",
    "DTZ007",
    "FBT001",
]
ignore = [
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "W191",
    "E402",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "D417",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "D212",
    "UP015", # redundant-open-modes, explicit is preferred

]
exclude = [
    "**/_vendor",
    "setuptools/_distutils",
    "setuptools/config/_validate_pyproject",
]

[lint.pydocstyle]
convention = "google"

[lint.isort]
force-single-line = false
force-wrap-aliases = false
lines-after-imports = false
lines-between-types = false
split-on-trailing-comma = false
