
// This file is auto-generated by the build script.
export interface HeroImage {
  imageName: string
  parent: string
  widths: {
    [key: number]: string
  }
  srcset: string
}

export const heroImages: HeroImage[] = [
  {
    parent: "docs/assets/images/hero/abstract",
    widths: {
      1280: "docs/assets/images/hero/abstract/abstract_1280.92bb4d97.avif",
      1920: "docs/assets/images/hero/abstract/abstract_1920.7475cf5a.avif",
      2560: "docs/assets/images/hero/abstract/abstract_2560.774883ee.avif",
      3840: "docs/assets/images/hero/abstract/abstract_3840.f45e7c84.avif"
    },
    srcset: "docs/assets/images/hero/abstract/abstract_1280.92bb4d97.avif 1280w, docs/assets/images/hero/abstract/abstract_1920.7475cf5a.avif 1920w, docs/assets/images/hero/abstract/abstract_2560.774883ee.avif 2560w, docs/assets/images/hero/abstract/abstract_3840.f45e7c84.avif 3840w",
    imageName: "abstract"
  },
  {
    parent: "docs/assets/images/hero/anime",
    widths: {
      1280: "docs/assets/images/hero/anime/anime_1280.3fcea899.avif",
      1920: "docs/assets/images/hero/anime/anime_1920.c254a9db.avif",
      2560: "docs/assets/images/hero/anime/anime_2560.d93b987e.avif",
      3840: "docs/assets/images/hero/anime/anime_3840.d38bd5ff.avif"
    },
    srcset: "docs/assets/images/hero/anime/anime_1280.3fcea899.avif 1280w, docs/assets/images/hero/anime/anime_1920.c254a9db.avif 1920w, docs/assets/images/hero/anime/anime_2560.d93b987e.avif 2560w, docs/assets/images/hero/anime/anime_3840.d38bd5ff.avif 3840w",
    imageName: "anime"
  },
  {
    parent: "docs/assets/images/hero/artbrut",
    widths: {
      1280: "docs/assets/images/hero/artbrut/artbrut_1280.9d423493.avif",
      1920: "docs/assets/images/hero/artbrut/artbrut_1920.b33e189e.avif",
      2560: "docs/assets/images/hero/artbrut/artbrut_2560.f941065b.avif",
      3840: "docs/assets/images/hero/artbrut/artbrut_3840.06f2db57.avif"
    },
    srcset: "docs/assets/images/hero/artbrut/artbrut_1280.9d423493.avif 1280w, docs/assets/images/hero/artbrut/artbrut_1920.b33e189e.avif 1920w, docs/assets/images/hero/artbrut/artbrut_2560.f941065b.avif 2560w, docs/assets/images/hero/artbrut/artbrut_3840.06f2db57.avif 3840w",
    imageName: "artbrut"
  },
  {
    parent: "docs/assets/images/hero/comic",
    widths: {
      1280: "docs/assets/images/hero/comic/comic_1280.80029dc5.avif",
      1920: "docs/assets/images/hero/comic/comic_1920.ccb36986.avif",
      2560: "docs/assets/images/hero/comic/comic_2560.2309f695.avif",
      3840: "docs/assets/images/hero/comic/comic_3840.d5bf4b07.avif"
    },
    srcset: "docs/assets/images/hero/comic/comic_1280.80029dc5.avif 1280w, docs/assets/images/hero/comic/comic_1920.ccb36986.avif 1920w, docs/assets/images/hero/comic/comic_2560.2309f695.avif 2560w, docs/assets/images/hero/comic/comic_3840.d5bf4b07.avif 3840w",
    imageName: "comic"
  },
  {
    parent: "docs/assets/images/hero/fanciful",
    widths: {
      1280: "docs/assets/images/hero/fanciful/fanciful_1280.97c5119b.avif",
      1920: "docs/assets/images/hero/fanciful/fanciful_1920.8a8d1e24.avif",
      2560: "docs/assets/images/hero/fanciful/fanciful_2560.d846fdc9.avif",
      3840: "docs/assets/images/hero/fanciful/fanciful_3840.2aa6eb29.avif"
    },
    srcset: "docs/assets/images/hero/fanciful/fanciful_1280.97c5119b.avif 1280w, docs/assets/images/hero/fanciful/fanciful_1920.8a8d1e24.avif 1920w, docs/assets/images/hero/fanciful/fanciful_2560.d846fdc9.avif 2560w, docs/assets/images/hero/fanciful/fanciful_3840.2aa6eb29.avif 3840w",
    imageName: "fanciful"
  },
  {
    parent: "docs/assets/images/hero/fantasy",
    widths: {
      1280: "docs/assets/images/hero/fantasy/fantasy_1280.cc724b8d.avif",
      1920: "docs/assets/images/hero/fantasy/fantasy_1920.b0945961.avif",
      2560: "docs/assets/images/hero/fantasy/fantasy_2560.87ecf4b7.avif",
      3840: "docs/assets/images/hero/fantasy/fantasy_3840.76aef34a.avif"
    },
    srcset: "docs/assets/images/hero/fantasy/fantasy_1280.cc724b8d.avif 1280w, docs/assets/images/hero/fantasy/fantasy_1920.b0945961.avif 1920w, docs/assets/images/hero/fantasy/fantasy_2560.87ecf4b7.avif 2560w, docs/assets/images/hero/fantasy/fantasy_3840.76aef34a.avif 3840w",
    imageName: "fantasy"
  },
  {
    parent: "docs/assets/images/hero/farcical",
    widths: {
      1280: "docs/assets/images/hero/farcical/farcical_1280.0bcf4abf.avif",
      1920: "docs/assets/images/hero/farcical/farcical_1920.eb4e92aa.avif",
      2560: "docs/assets/images/hero/farcical/farcical_2560.b70c1efb.avif",
      3840: "docs/assets/images/hero/farcical/farcical_3840.512c28b7.avif"
    },
    srcset: "docs/assets/images/hero/farcical/farcical_1280.0bcf4abf.avif 1280w, docs/assets/images/hero/farcical/farcical_1920.eb4e92aa.avif 1920w, docs/assets/images/hero/farcical/farcical_2560.b70c1efb.avif 2560w, docs/assets/images/hero/farcical/farcical_3840.512c28b7.avif 3840w",
    imageName: "farcical"
  },
  {
    parent: "docs/assets/images/hero/fauvist",
    widths: {
      1280: "docs/assets/images/hero/fauvist/fauvist_1280.9e323bee.avif",
      1920: "docs/assets/images/hero/fauvist/fauvist_1920.e5d68503.avif",
      2560: "docs/assets/images/hero/fauvist/fauvist_2560.e70f1931.avif",
      3840: "docs/assets/images/hero/fauvist/fauvist_3840.500219d3.avif"
    },
    srcset: "docs/assets/images/hero/fauvist/fauvist_1280.9e323bee.avif 1280w, docs/assets/images/hero/fauvist/fauvist_1920.e5d68503.avif 1920w, docs/assets/images/hero/fauvist/fauvist_2560.e70f1931.avif 2560w, docs/assets/images/hero/fauvist/fauvist_3840.500219d3.avif 3840w",
    imageName: "fauvist"
  },
  {
    parent: "docs/assets/images/hero/minimal",
    widths: {
      1280: "docs/assets/images/hero/minimal/minimal_1280.42dcf0b0.avif",
      1920: "docs/assets/images/hero/minimal/minimal_1920.71ca07e0.avif",
      2560: "docs/assets/images/hero/minimal/minimal_2560.c5549cbf.avif",
      3840: "docs/assets/images/hero/minimal/minimal_3840.6c643286.avif"
    },
    srcset: "docs/assets/images/hero/minimal/minimal_1280.42dcf0b0.avif 1280w, docs/assets/images/hero/minimal/minimal_1920.71ca07e0.avif 1920w, docs/assets/images/hero/minimal/minimal_2560.c5549cbf.avif 2560w, docs/assets/images/hero/minimal/minimal_3840.6c643286.avif 3840w",
    imageName: "minimal"
  },
  {
    parent: "docs/assets/images/hero/mystical",
    widths: {
      1280: "docs/assets/images/hero/mystical/mystical_1280.f50a7c79.avif",
      1920: "docs/assets/images/hero/mystical/mystical_1920.14eadafd.avif",
      2560: "docs/assets/images/hero/mystical/mystical_2560.31500c69.avif",
      3840: "docs/assets/images/hero/mystical/mystical_3840.67cbaa60.avif"
    },
    srcset: "docs/assets/images/hero/mystical/mystical_1280.f50a7c79.avif 1280w, docs/assets/images/hero/mystical/mystical_1920.14eadafd.avif 1920w, docs/assets/images/hero/mystical/mystical_2560.31500c69.avif 2560w, docs/assets/images/hero/mystical/mystical_3840.67cbaa60.avif 3840w",
    imageName: "mystical"
  },
  {
    parent: "docs/assets/images/hero/surreal",
    widths: {
      1280: "docs/assets/images/hero/surreal/surreal_1280.aebe2db9.avif",
      1920: "docs/assets/images/hero/surreal/surreal_1920.e5c0cbd2.avif",
      2560: "docs/assets/images/hero/surreal/surreal_2560.484a1d5c.avif",
      3840: "docs/assets/images/hero/surreal/surreal_3840.6fd8d29c.avif"
    },
    srcset: "docs/assets/images/hero/surreal/surreal_1280.aebe2db9.avif 1280w, docs/assets/images/hero/surreal/surreal_1920.e5c0cbd2.avif 1920w, docs/assets/images/hero/surreal/surreal_2560.484a1d5c.avif 2560w, docs/assets/images/hero/surreal/surreal_3840.6fd8d29c.avif 3840w",
    imageName: "surreal"
  }
] as const
