authors:
  seekinginfiniteloop:
    name: Adam Poulemanos
    description: founder of Plain License
    avatar: https://avatars.githubusercontent.com/u/89049923
    url: https://github.com/seekinginfiniteloop
    email: adam@plainlicense.org
