name: CI/CD

on:
  push:
    paths:
      - 'docs/**/licenses/*'
      - 'docs/**/versions/*'
    branches:
      - dev
  pull_request:
    paths:
      - 'docs/**/licenses/*'
      - 'docs/**/versions/*'
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: plainlicense.org
          EXTRA_PACKAGES: build-base
          # REQUIREMENTS: folder/requirements.txt

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Markdown links
        uses: byrnereese/github-action-mkdocs-link-check@v1
        with:
          use-verbose-mode: 'yes'
          folder-path: 'docs/'
          file-path: './README.md, ./UNLICENSE.md, ./CONTRIBUTING.md'

      - name:  Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          fix: true
          globs: '**/*.md'
    
