name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'docs/**/licenses/*'
      - 'docs/**/versions/*'
      - 'mkdocs.yml'
      - '.github/workflows/ci.yml'
    branches:
      - dev

permissions:
  contents: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-static-i18n[material] mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-material[imaging]
      - run: mkdocs gh-deploy --force
