name: CI/CD

on:
  push:
    paths:
      - 'docs/**/licenses/*'
      - 'docs/**/versions/*'
      - './mkdocs.yml'
      - './.github/workflows/ci.yml'
    branches:
      - dev


permissions:
  contents: write

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name:  Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          fix: true
          globs: '**/*.md'


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: "pip install mkdocs-static-i18n[material]"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
