name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
    paths:
      - "docs/**/licenses/*"
      - "docs/**/versions/*"
      - "mkdocs.yml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-static-i18n[material] mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-material[imaging] pygments mkdocs-rss-plugin mkdocs[i18n] pymdown-extensions
      - name: Build and deploy
        id: deployment
        run: mkdocs gh-deploy --force
