name: Release and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Node dependencies
        run: npm ci
      - name: Generate changelog
        run: node generate-changelog.js
      - name: Release project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npx semantic-release
      - name: Release individual licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for license in docs/licenses/*/*/; do
            if [ -f "$license/package.json" ]; then
              echo "Releasing $license"
              (cd $license && npx semantic-release -e ../../../.releaserc.json)
            fi
          done
      - name: Commit updated changelogs
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add CHANGELOG.md docs/licenses/**/CHANGELOG.md
          git diff-index --quiet HEAD || git commit -m "docs: update changelogs [skip ci]"
          git push

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          export PYTHONPATH=$PYTHONPATH:custom_extensions
          pip install --upgrade pip
          pip install markdown pymdown-extensions mkdocs-material[imaging] mkdocs-static-i18n[material] mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-rss-plugin mkdocs[i18n] pygments pyyaml mkdocs-hooks-plugin
      - name: Build and deploy
        id: deployment
        run: mkdocs gh-deploy --force

  notify:
    needs: [release, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Workflow failed: ${{ github.workflow }}',
              body: 'Workflow ${{ github.workflow }} failed on commit ${{ github.sha }}. Check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })
