name: Update Sponsors Progress

on:
  schedule:
    - cron: "10 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering
  workflow_run: # Allows triggering from other workflows
    branches: [main]
    workflows: ["Release, Build, and Deploy"]
    types:
      - completed

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ez-yaml

      - name: Update sponsors progress
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/scripts/update_sponsors.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "bot(site): Update sponsors progress" && git push)
